### PR TITLE
Added earnings by day request.

### PR DESCRIPTION
**Pull request by mccabe93**

### CODE REVIEW

**Comment by cosmincatalin** [comment]
I am on holiday and just saw your PR. I'll take a look and then merge it in if I see no issues. Your contribution is greatly appreciated.

**Review by cosmincatalin — CHANGES_REQUESTED** [review]
The `.vs` folder looks like it contains Visual Studio specific files, so unless it adds some general value, please remove it from the merge.

**Review by cosmincatalin — APPROVED** [review]

**Comment by cosmincatalin** [comment]
I have to fix an issue before this can get merged in. I'm on it right now.

**Comment by mccabe93** [comment]
> I have to fix an issue before this can get merged in. I'm on it right now.

Ah sorry, been swamped with work. Appreciate you picking up my slack 😆 Happy to contribute, this library is super helpful!

**Comment by cosmincatalin** [comment]
I've just released a new version (0.0.8) with your changes in.
I'll probably start working on a new 1.0.0 version with breaking changes...2 years later, I have new ideas 😄

**Pull request merged**
